/*
 * stoplight-studio-test-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PatchUsersUserIdRequest struct {

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	// If a new email is given, the user's email verified property will be set to false.
	Email string `json:"email,omitempty"`

	DateOfBirth string `json:"dateOfBirth,omitempty"`
}

// AssertPatchUsersUserIdRequestRequired checks if the required fields are not zero-ed
func AssertPatchUsersUserIdRequestRequired(obj PatchUsersUserIdRequest) error {
	return nil
}

// AssertRecursePatchUsersUserIdRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PatchUsersUserIdRequest (e.g. [][]PatchUsersUserIdRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePatchUsersUserIdRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPatchUsersUserIdRequest, ok := obj.(PatchUsersUserIdRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPatchUsersUserIdRequestRequired(aPatchUsersUserIdRequest)
	})
}
